import type { Car } from './favorite.service';

export const CAR_DATABASE: Car[] = [
    {
      id: 1,
      name: 'BMW M5 Competition',
      brand: 'BMW',
      model: 'M5 Competition',
      year: 2023,
      price: 115900,
      mileage: 15000,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      rating: 5,
      image: 'https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=800&q=80',
      isFavorite: false,
      features: ['Leather Seats', 'Sunroof', 'Navigation', 'Premium Sound'],
      type: 'Sedan'
    },
  {
    id: 2,
    name: 'BMW X6 M Competition',
    brand: 'BMW',
    model: 'X6 M Competition',
    year: 2023,
    price: 108900,
    mileage: 12000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
      rating: 4,
      image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
      isFavorite: false,
      features: ['360 Camera', 'Heated Seats', 'Panoramic Sunroof', 'Air Suspension'],
      type: 'SUV'
    },
  {
    id: 3,
    name: 'Mercedes-Benz GLE 450',
    brand: 'Mercedes-Benz',
    model: 'GLE 450',
    year: 2023,
    price: 63500,
    mileage: 12000,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
      rating: 4,
      image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
      isFavorite: false,
      features: ['360 Camera', 'Heated Seats', 'Panoramic Sunroof', 'Air Suspension'],
      type: 'SUV'
    },
  {
    id: 4,
    name: 'Mercedes-Benz S-Class',
    brand: 'Mercedes-Benz',
    model: 'S 580',
    year: 2023,
    price: 116500,
    mileage: 8000,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
      rating: 5,
      image: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=800&q=80',
      isFavorite: false,
      features: ['Massaging Seats', 'Air Purification', 'Burmester Sound', 'Magic Sky Control'],
      type: 'Sedan'
    },
  {
    id: 5,
    name: 'Audi RS7 Sportback',
    brand: 'Audi',
    model: 'RS7 Sportback',
    year: 2023,
    price: 119900,
    mileage: 8500,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
      rating: 5,
      image: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=800&q=80',
      isFavorite: false,
      features: ['Quattro AWD', 'Virtual Cockpit', 'Matrix LED Headlights', 'Bang & Olufsen Sound'],
      type: 'Coupe'
    },
  {
    id: 6,
    name: 'Audi Q8',
    brand: 'Audi',
    model: 'Q8',
    year: 2023,
    price: 84700,
    mileage: 10000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
      rating: 4,
      image: 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=800&q=80',
      isFavorite: false,
      features: ['Virtual Cockpit Plus', 'Matrix LED Headlights', 'Panoramic Sunroof', 'Valcona Leather'],
      type: 'SUV'
    },
  {
    id: 7,
    name: 'Tesla Model S Plaid',
    brand: 'Tesla',
    model: 'Model S Plaid',
    year: 2023,
    price: 135990,
    mileage: 5000,
    fuelType: 'Electric',
    transmission: 'Automatic',
      rating: 5,
      image: 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=800&q=80',
      isFavorite: false,
      features: ['Autopilot', '17-inch Touchscreen', 'Premium Interior', 'Ludicrous Mode'],
      type: 'Sedan'
    },
  {
    id: 8,
    name: 'Tesla Model 3',
    brand: 'Tesla',
    model: 'Model 3',
    year: 2023,
    price: 42990,
    mileage: 15000,
    fuelType: 'Electric',
    transmission: 'Automatic',
      rating: 4,
      image: 'https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=800&q=80',
      isFavorite: false,
      features: ['Autopilot', 'Premium Interior', 'Supercharging', 'OTA Updates'],
      type: 'Sedan'
    },
  {
    id: 9,
    name: 'Toyota Camry TRD',
    brand: 'Toyota',
    model: 'Camry TRD',
    year: 2023,
    price: 32485,
    mileage: 20000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
      rating: 4,
      image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
      isFavorite: false,
      features: ['TRD Sport Suspension', '19-inch Wheels', 'Unique Styling', '8-inch Touchscreen'],
      type: 'Sedan'
    },
  {
    id: 10,
    name: 'Toyota RAV4 Hybrid',
    brand: 'Toyota',
    model: 'RAV4 Hybrid',
    year: 2023,
    price: 28475,
    mileage: 18000,
    fuelType: 'Hybrid',
    transmission: 'CVT',
      rating: 5,
      image: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=800&q=80',
      isFavorite: false,
      features: ['Hybrid System', 'Apple CarPlay', 'Safety Sense 2.0', 'Power Liftgate'],
      type: 'SUV'
    },
  {
    id: 11,
    name: 'Honda Civic Type R',
    brand: 'Honda',
    model: 'Civic Type R',
    year: 2023,
    price: 38950,
    mileage: 12000,
    fuelType: 'Gasoline',
    transmission: 'Manual',
      rating: 5,
      image: 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=800&q=80',
      isFavorite: false,
      features: ['Turbo Engine', 'Recaro Seats', 'Brembo Brakes', 'Adaptive Damper System'],
      type: 'Sedan'
    },
  {
    id: 12,
    name: 'Honda Accord',
    brand: 'Honda',
    model: 'Accord',
    year: 2023,
    price: 26520,
    mileage: 15000,
    fuelType: 'Gasoline',
    transmission: 'CVT',
      rating: 4,
      image: 'https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=800&q=80',
      isFavorite: false,
      features: ['Honda Sensing Suite', 'Wireless Charging', 'Apple CarPlay', 'LaneWatch'],
      type: 'Sedan'
    },
  {
    id: 13,
    name: 'Ford Mustang GT',
    brand: 'Ford',
    model: 'Mustang GT',
    year: 2023,
    price: 37965,
    mileage: 10000,
    fuelType: 'Gasoline',
    transmission: 'Manual',
      rating: 5,
      image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
      isFavorite: false,
      features: ['5.0L V8 Engine', 'MagneRide Damping', 'Track Apps', '12-Speaker Audio'],
      type: 'Coupe'
    },
  {
    id: 14,
    name: 'Ford F-150 Raptor',
    brand: 'Ford',
    model: 'F-150 Raptor',
    year: 2023,
    price: 65495,
    mileage: 8000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
      rating: 5,
      image: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=800&q=80',
      isFavorite: false,
      features: ['High-Performance Off-Road', 'FOX Shocks', 'Terrain Management', '12.4-inch Touchscreen'],
      type: 'Pickup'
    },
  {
    id: 15,
    name: 'Nissan GT-R',
    brand: 'Nissan',
    model: 'GT-R Premium',
    year: 2023,
    price: 113540,
    mileage: 5000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
      rating: 5,
      image: 'https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=800&q=80',
      isFavorite: false,
      features: ['All-Wheel Drive', 'Premium Interior', 'Premium Sound', 'Advanced Climate'],
      type: 'Coupe'
    },
  {
    id: 16,
    name: 'Nissan Altima',
    brand: 'Nissan',
    model: 'Altima SR',
    year: 2023,
    price: 26850,
    mileage: 14000,
    fuelType: 'Gasoline',
    transmission: 'CVT',
      rating: 4,
      image: 'https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=800&q=80',
      isFavorite: false,
      features: ['ProPILOT Assist', 'NissanConnect', 'Apple CarPlay', 'Wireless Charging'],
      type: 'Sedan'
    }
];
